### PR TITLE
Add support for validating against OAS v3 schema

### PR DESCRIPTION
**Pull request by theaxel**

### CODE REVIEW

**Comment by theaxel** [comment]
Any idea why travis doesn't pickup to build this PR @ketiko ?

**Comment by ketiko** [comment]
Thanks for contributing!  I'll take a look at the build.

I'm curious how you are documenting your swagger 3.0 schema.  Are you doing it in code or in a separate json file?  I've been using https://github.com/fotinakis/swagger-blocks but haven't migrated to v3 which it doesn't support.

**Comment by theaxel** [comment]
Thanks. I played around with https://github.com/readmeio/oas to have inline doc blocks that are then converted into proper swagger json. 
Another one is https://github.com/domaindrivendev/rswag which builds the schema from your test specs. Only using the rails engine right now to provide a swagger-ui.
So far haven't come to a final solution yet what the best tool/way to go is.

**Comment by ketiko** [comment]
I've got to figure out this build thing but this PR looks good and it works for me in my other projects.  I'm going to merge and release this now, then I'll fix the build later.

Thanks again for adding this!

**Review by ketiko — APPROVED** [review]

**Pull request merged**
